# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    env_file:
      - .env
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}
    #environment:
    #  POSTGRES_DB: movies
    #  POSTGRES_USER: biso
    #  POSTGRES_PASSWORD: abc123

  cache:
    image: redis
    env_file:
      - .env
    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - 127.0.0.1:${REDIS_POST}:${REDIS_PORT}
