# Use postgres/example user/password credentials
version: '3.9'

services:

  api:
    build: .
    command: bash -c "alembic upgrade head && task run-prod"
    env_file:
      - .env
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
  
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis
    env_file:
      - .env
    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
